### ISSUE TITLE
What about the particles?

### ISSUE THREAD

**Issue by PursuitDream** [luxeengine/support#11]
Hey, here's a question: Is there any specific reference to work with particles? Or tutorials?
I looked through a lot of different examples, but it is still not clear for me.
Now, specific questions:
1. By default, the objects are generated by a square shape. But I want to use the circles, how?
2. What's with textures?
3. Is there importer for JSON parameters?

And it would be nice if you show an example with the snow.

**Comment by underscorediscovery** [comment]
Have you looked at tests/features/particles? There is snow of sorts in the samples/alphas/02_0010 as well a moving the systems round. 

They are rudimentary particles so no, they only support quads (sprites) but circles would be quite a lot of vertices more so quads are cheaper on that front. You'd just apply a texture for a circle ideally one close to the edges for less overdraw. 

I don't recall if there is json specifically but remember that you can pass the Dynamic as if it were a typeset, and cast it to the typedef in haxe. In other words, just pass the JSON object to the particle constructor after adding the necessary additional flags to it before you do.

Let me know if that helps so long.

**Comment by PursuitDream** [comment]
Thanks for your help. Now I haven't any questions.
