### ISSUE TITLE
Unable to compile empty project for android on mac

### ISSUE THREAD

**Issue by kevinresol** [luxeengine/support#14]
haxe: 9047be8
hxcpp: 3.4.49
macOS 10.12.3

In folder `samples/empty` run `flow run android`
Add `defines: ['ANDROID_NDK_DIR=/usr/local/Cellar/android-ndk']` to flow file
Then open `android.project` in Android Studio
Then run the project:

```
Creating /usr/local/Cellar/haxe/HEAD-9047be8/lib/haxe/lib/luxe/git/samples/empty/bin/android.build/cpp/obj/android-v7/__pch/haxe/hxcpp.h.gch...
/usr/local/Cellar/haxe/HEAD-9047be8/lib/haxe/lib/hxcpp/3,4,49/include/hxcpp.h:19:23: fatal error: typeinfo: No such file or directory
    #include <typeinfo>
```

I have `r13b` folder in my NDK DIR.

ios project compiles fine though.

**Comment by underscorediscovery** [comment]
Seems this might be hxcpp related, seems some mentions of the c++ lib needing to be GNU libstdc++ to find typeinfo? Not sure, I'm checking stuff on my end with an older ndk, but maybe @hughsando  has seen something related.

**Comment by kevinresol** [comment]
So "the c++ lib needing to be GNU libstdc++" means the NDK here?
I am not very familiar with c++, does libstdc++ a newer thing or older thing?

**Comment by underscorediscovery** [comment]
It was just something I noticed on a thread, till we can look closer at what changed (hxcpp/ndk) in detail I wouldn't do anything with flipping switches. The ndk for me builds without typeinfo errors but it hits this:

```
Error: In file included from include/snow/core/native/io/IO.h:14:0,
                 from ./src/snow/systems/io/IO.cpp:44:
/Users/sven/dev/snowkit/linc/sdl//linc/linc_sdl.h:3:19: fatal error: /Users/sven/.hxcpp_cache/haxe/pch9a2e446e/hxcpp.h: No such file or directory
 #include <hxcpp.h>
                   ^
compilation terminated.
```

Which I think relates to https://github.com/HaxeFoundation/hxcpp/issues/559#issuecomment-277842526 since I noticed that last night.

**Comment by hughsando** [comment]
I would guess that the generation of the pch9a2e446e/hxcpp.h file failed earlier in the build, and that is why it can't be found. Not sure why it did not halt earlier though.
As for the typeinfo, maybe google  moved stuff around.  Although, I have r13b on windows and it seems ok.

**Comment by kevinresol** [comment]
Does this help?

```
Kevins-MacBook-Pro:r13b kevin$ find . -name typeinfo
./sources/cxx-stl/gabi++/include/typeinfo
./sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo
./sources/cxx-stl/gnu-libstdc++/include/typeinfo
./sources/cxx-stl/llvm-libc++/include/typeinfo
./sources/cxx-stl/stlport/stlport/typeinfo
./sources/cxx-stl/system/include/typeinfo
```
