### ISSUE TITLE
update window title post-configuration

### ISSUE THREAD

**Issue by chutchinson** [luxeengine/support#19]
Is it possible to change the window title post-configuration? I scanned through **snow** and I am struggling to find a way to do this; it's possible to change the window / application title in all of the supported platforms so I would expect this to be exposed.

Is there anything clever I can do?

Thanks!

**Comment by underscorediscovery** [comment]
Hi, on native targets, just use the SDL API directly. You have access to almost the whole API, and It lives in the `sdl` package, so you can do `import sdl.SDL;` or just `sdl.SDL.setWindowTitle(Luxe.snow.runtime.window);`

On web platform, this is similar, just use `js.html.*` API from haxe itself i.e `js.Browser.window.title = 'web'`;

**Comment by chutchinson** [comment]
I'm blown away by the response time and the quality of the APIs (snow / luxe / flow); I actually discovered the native solution on my own and was about to post a response to help others. 

Thank you!

**Comment by underscorediscovery** [comment]
Thanks, glad to help.
