### ISSUE TITLE
Approaches to gui? Possible to import nuklear ui?

### ISSUE THREAD

**Issue by fire** [luxeengine/support#21]
What are your approaches to user interfaces?

I was thinking of importing https://github.com/vurtun/nuklear, but I'm not familiar with haxe and its c import pipeline.

A goal is to support web browsers.

**Comment by underscorediscovery** [comment]
You won't be able to support browsers (as easily) with C based stuff. 

Try [mint](http://snowkit.github.io/mint/)
or [haxeui 2 with a luxe backend](https://github.com/haxeui/haxeui-luxe) for now.

It will depend on what you're making too.

**Comment by fire** [comment]
Well I wanted to work on a 3d game in lexeengine and I had some experiences with nuklear. I saw some reports of emscriptem / wasm. Is that viable.

**Comment by underscorediscovery** [comment]
If you're referring to the dev log # 4 regarding 1.0 stuff - then that isn't related to the current code. The current code runs on haxe and if you read all the previous dev logs (1/2/3) will have seen the direction there.

The current codebase has not been tested with emscripten. 

I know hxcpp (the haxe cpp backend) has emscripten flags so potentially you could configure it to give you an emscripten build but I have never tried and I don't intend to invest time into exploring that idea at the moment.
