### ISSUE TITLE
luxe.GameConfig type not found

### ISSUE THREAD

**Issue by ghost** [luxeengine/support#22]
When compiling a luxe engine test on ArchLinux, it throws the error:
    
    flow / 1.0.0-alpha.2 (node.js v0.12.7)
    flow / target is linux ( arch 64 )
    flow / haxe version 3.4.2
    
    flow / build - LuxeTest1 0.0.0 for linux
    flow / build - running haxe ...
    src/Main.hx:1: characters 7-22 : Type not found : luxe.GameConfig

**Comment by underscorediscovery** [comment]
Hi, can you tell me what version of luxe and where the project came from? 
like did you just install everything or was this project from before?

**Comment by slothh** [comment]
Which ever the newest version downloadable from HaxeLib is. I installed yesterday at about ~5pm. The project wasn't made from a template. The flow file has name, author, and version in it. The Main class only has a config function and an empty ready function; it also includes luxe.GameConfig

**Comment by slothh** [comment]
By "which ever the newest version available from HaxeLib". I mean, whichever version of luxe is downloaded via snowfall, where snowfall is downloaded from HaxeLib.

**Comment by underscorediscovery** [comment]
Can you compare the project with [this empty project](https://github.com/underscorediscovery/luxe/tree/master/samples/empty)?

**Comment by slothh** [comment]
I tried running directly from the 'luxe/samples/empty' project, which I found in: ~/.haxe/lib/luxe/git/. It chucked an error about not being able to include <hxcpp.h> in an 'IO.hx' file. I don't know what the issue could be as I have installed hxcpp.h. I will try including that in a C++ project of my own tomorrow, but for now I need to sleep, it's 1:29 in the morning where I am.

**Comment by slothh** [comment]
Sorry for not being able to help with the issue now.

**Comment by underscorediscovery** [comment]
No problem, let me know [if this helps](https://github.com/underscorediscovery/luxe/issues/417#issuecomment-280361379) when you get back to it regarding the hxcpp issue.

**Comment by slothh** [comment]
Sorry I haven't replied un till now. I've only just suddenly remembered about the problem.
Adding the `'NO_PRECOMPILED_HEADERS'` define and the `dependencies: luxe '*'` fixed my problem, that was for build. Although, I will note, that flow could not run  the executable, I had to chmod it for it to be able to run.

**Comment by underscorediscovery** [comment]
That's definitely not normal, [as it runs chmod](https://github.com/snowkit/flow/blob/master/src/flow/cmd/build/build.cpp.js#L179) when doing a build already. Not sure what that's about, but `flow log --3` or 4 adds a lot more detail to debug things.
