### ISSUE TITLE
is luxe going to be opensource? 👀

### ISSUE THREAD

**Issue by endel** [luxeengine/support#28]
I've recently heard of Wren and Luxe, and it all sounds very exciting! Thanks for making Wren open-source. Would Luxe be open-source as well as its previous version written in Haxe?

Keep on rocking! Cheers!

**Comment by underscorediscovery** [comment]
That's the goal, yea.

**Comment by endel** [comment]
Awesome, thanks! I can only imagine the amount of work you have on your plate! Wren and Luxe sounds all very exciting, good luck with your projects!

**Comment by underscorediscovery** [comment]
No worries, and for clarity, I am maintaining Wren but @munificent is the one that made it, and open sourced it.
