### ISSUE TITLE
How to handle higher resolution screens?

### ISSUE THREAD

**Issue by hexdie** [luxeengine/support#3]
I guess I'll be the first asking a question here :D

I haven't really utilized the web target until recently and I noticed an issue on higher resolution screens  where my viewport is twice the size that I actually set. I first noticed it on a macbook pro, but I was able to reproduce it with the chrome device emulator.

This is how the game is intended to look:

![devicescale1](https://cloud.githubusercontent.com/assets/9022850/17991441/57140286-6b04-11e6-88b8-36fd13c1dd1e.png)

And this is how it is displaying on higher resolution displays:

![devicescale2](https://cloud.githubusercontent.com/assets/9022850/17991453/6cecbc7e-6b04-11e6-82f9-16ba583eaebc.png)

So my question is, how do I go about making it look like that first image on higher resolution displays?

Here's the source in case it's helpful: https://bitbucket.org/hexdie/onebuttonjam16/src

Thanks!

**Comment by nebbishhacker** [comment]
The simplest solution I can think of is to set the camera size explicitly in `ready()`, like so:
```
Luxe.camera.size = new Vector(gameResolution.x, gameResolution.y);
```
That way regardless of the canvas size, things should still be scaled appropriately.

**Comment by hexdie** [comment]
Thanks @underscorediscovery! That does clarify things. The camera size mode seems most applicable to my situation, so I'll try getting that to work tonight.

**Comment by underscorediscovery** [comment]
For anyone reading this after the fact, the default behaviour has changed to be more user friendly. The full details are posted in this status post: https://luxeengine.com/dev-status-2/
