### ISSUE TITLE
Drawing to texture

### ISSUE THREAD

**Issue by CarlOlson** [luxeengine/support#5]
If I wanted to use the draw API to create many similar objects, wouldn't it be best to render once to a texture then use that texture for my objects?

How could this be done with Luxe?

**Comment by underscorediscovery** [comment]
You could do that if you like yes. Usually, you would create a batcher to render the geometry together, then you draw it into a texture.

[You can see an example here](https://github.com/underscorediscovery/luxe/tree/master/tests/rendering/rendertexture)

But, if you're rendering many things like tiles - then there are available flags for handling this. See for instance, [this quadpack](https://github.com/underscorediscovery/luxe/tree/master/tests/features/quadpack_geometry) test which uses the `locked` flag of geometry to only submit the geometry once, therefore drawing very cheaply.

If you need more details, you will have to provide more of what you're trying to do :)
