### ISSUE TITLE
Can't get anything working on Mac

### ISSUE THREAD

**Issue by songproducer** [luxeengine/support#7]
I'm running this command:

haxelib run flow launch

and I get:

```
flow / process util - failed to run : /Users/leotreasure/luxe/samples/examples/platformer/bin/mac64/luxe_platformer.app/Contents/MacOS/luxe_platformer 
flow / process util - { [Error: spawn /Users/leotreasure/luxe/samples/examples/platformer/bin/mac64/luxe_platformer.app/Contents/MacOS/luxe_platformer ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /Users/leotreasure/luxe/samples/examples/platformer/bin/mac64/luxe_platformer.app/Contents/MacOS/luxe_platformer',
  path: '/Users/leotreasure/luxe/samples/examples/platformer/bin/mac64/luxe_platformer.app/Contents/MacOS/luxe_platformer' }
```

**Comment by underscorediscovery** [comment]
Have you run a build before that?

The command to run is `flow run`, launch expects `build` to have happened before.

`flow build` = just build
`flow run` = build + launch
`flow launch` = just launch (expects build to have happened once)

**Comment by songproducer** [comment]
I'm not quite sure how to run flow directly, I tried to install it again with:

haxelib install flow 0.0.0

now when I try:

haxelib run flow build

I get:

`Library flow version 0.0.0 does not have a run script`

**Comment by underscorediscovery** [comment]
You can't install flow from haxelib at the moment.
You should follow the instructions here for setup : https://luxeengine.com/get

I've updated the instructions to mention `haxelib run snowfall shortcuts` which will set up a `flow` shortcut without the `haxelib` prefix for you.

**Comment by underscorediscovery** [comment]
Since I haven't heard back in a while, feel free to reopen the issue if you're still stuck, but I'm going to close it for now.
