### ISSUE TITLE
Build Size

### ISSUE THREAD

**Issue by rgrams** [luxeengine/support#8]
Hi all. I just started trying out Luxe and I compiled a windows release build of my tiny test project. The resulting .exe is about six megabytes, which seems rather large. Is that normal/expected? 

I'm basically still following the beginner's guide at this point. I used `flow run` and I'm looking at the .exe in bin/windows in my project folder.

**Comment by anissen** [comment]
I don't know what the usual build size is on Windows. Things you can do to minimize the build size:
* Ensure that you're building for release and with dead-code elimination enabled
* Run [UPX packer](https://upx.github.io/) on the build output

**Comment by CamperPR** [comment]
I think it's normal for windows build. So, I compiled luxe sample test and my last game, they both have sizes near 6 megabytes, too.

**Comment by underscorediscovery** [comment]
Zipped builds are usually around ~1mb so it's rarely come up. 

It's worth mentioning that UPX will be redundant if you're shipping in a zip file or any other compressed format (steam, ios, etc) and UPX can be troublesome with antivirus on Windows (it can be false flagged pretty easily).

There are probably a few flags to bring it down a bit but in practice you've got all the Haxe code, SDL and a few other libraries in there - at some point you'll reach the minimum viable amount anyway. 

As it hasn't been too relevant, I haven't tested binary sizes much but I'll see if I can take a look at the windows flags (if any) - and as anissen mentions make sure `-dce full` is enabled if possible, this cut ~2mb on my quick test on mac:

```js
    build : {
      flags: ['-dce full'],
      dependencies : {
        luxe : '*'
      }
    },
```

**Comment by rgrams** [comment]
OK, thanks for the quick answers guys! Yup, the dce flag cut off 1mb for me. 

Yeah, this kind of size is definitely not an issue for me, it's at most a third of the minimum build size of any other engine I've tried. I was reading the [Porting QWOP](http://snowkit.org/2015/08/06/case-study-qwop/) article, and he says the minimum build size is 120kb, so I thought I was doing something totally wrong. But I guess he's talking about building for web, so a totally different animal.

**Comment by underscorediscovery** [comment]
Yep, it was for web.
