### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by xyroclast** [luxeengine/support#9]
Hi there,
Just wanted to let you know that the HaxeDevelop setup instructions link no longer works, at the bottom of the following page: https://luxeengine.com/setup-an-ide/
Cheers!

**Comment by underscorediscovery** [comment]
Aha, it was both the top and bottom one, where I fixed the one link on the `a` tag and not on the `img` itself. Thanks, both are fixed.

**Comment by xyroclast** [comment]
Awesome, thanks for the quick solve!
